# Generated by Django 5.2.4 on 2025-07-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'group')},
        ),
    ]
